apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: shared-resource-acs-api-token
  namespace: stackrox
rules:
  - apiGroups:
      - sharedresource.openshift.io
    resources:
      - sharedsecrets
    resourceNames:
      - acs-shared-token
    verbs:
      - use