apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
 name: shared-resource-quay-api-token
 namespace: openshift-operators
roleRef:
 apiGroup: rbac.authorization.k8s.io
 kind: Role
 name: shared-resource-quay-api-token
subjects:
 - kind: ServiceAccount
   name: builder
   namespace: {{ .Values.devel.namespace }}