apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: shared-resource-quay-api-token
  namespace: openshift-operators
rules:
  - apiGroups:
      - sharedresource.openshift.io
    resources:
      - sharedsecrets
    resourceNames:
      - quay-shared-token
    verbs:
      - use