apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: containers-pvc
  namespace: {{ .Values.global.devel.namespace }}  
spec:
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
#  persistentVolumeReclaimPolicy: Retain